apiVersion: v1
kind: Service
metadata:
  name: csi-nginx
  labels:
    app: csi-nginx
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: csi-nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: csi-nginx # has to match .spec.template.metadata.labels
  serviceName: "csi-nginx"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: csi-nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          image: k8s.gcr.io/nginx-slim:0.8
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "cbs-csi"
        resources:
          requests:
            storage: 10Gi
