---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tencentcloud-csi-attacher
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tencentcloud-external-attacher-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tencentcloud-csi-attacher-role
subjects:
  - kind: ServiceAccount
    name: tencentcloud-csi-attacher
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: tencentcloud-external-attacher-runner
  apiGroup: rbac.authorization.k8s.io
