---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-cbsplugin-attacher
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-cbsplugin-attacher
  template:
    metadata:
      labels:
        app: csi-cbsplugin-attacher
    spec:
      hostNetwork: true
      serviceAccountName: tencentcloud-csi-attacher
      nodeSelector:
        kubernetes.io/os: linux
      # priorityClassName: system-cluster-critical
      # tolerations:
      #   - key: "node-role.kubernetes.io/master"
      #     operator: "Equal"
      #     value: "true"
      #     effect: "NoSchedule"
      containers:
        - name: csi-cbsplugin-attacher
          image: quay.io/k8scsi/csi-attacher:v2.1.1
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            # - "-timeout=120s"
            # - "-leader-election"
            # - "-leader-election-type=leases"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/com.tencent.cloud.csi.cbs
            type: DirectoryOrCreate
